name: Production deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TARGET_FOLDER: "/var/www/hirelancer/client"

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HIRELANCER_HOST }}
        USERNAME: ${{ secrets.HIRELANCER_USERNAME }}
        PORT: ${{ secrets.HIRELANCER_PORT }}
        KEY: ${{ secrets.HIRELANCER_SECRET }}
        source: "."
        target: "${{ env.TARGET_FOLDER }}"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HIRELANCER_HOST }}
        USERNAME: ${{ secrets.HIRELANCER_USERNAME }}
        PORT: ${{ secrets.HIRELANCER_PORT }}
        KEY: ${{ secrets.HIRELANCER_SECRET }}
        script_stop: true
        script: |
          git --work-tree="${{ env.TARGET_FOLDER }}" --git-dir="${{ env.TARGET_FOLDER }}/.git" clean -f .
          yarn --cwd "${{ env.TARGET_FOLDER }}"
          yarn --cwd "${{ env.TARGET_FOLDER }}" run build
          pm2 restart hirelancer
